id: I8E9706ED
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:14:46.382360
last_modified: 2023-02-10 00:14:46.382505
source_metadata:
  title: 'MSV 6,04: Pañcaka'
  language: bo
bases:
  '7164':
    base_file: 7164.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
